"""Generate the Website 2.0 PRE band view from the canonical public master."""
from __future__ import annotations
import json, shutil
from html import escape
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]; C=ROOT/"content"/"website_v2"; OUT=ROOT/"candidate"/"website-v2-0"
CSS='''*{box-sizing:border-box}body{margin:0;font-family:Pretendard,"Noto Sans KR","Malgun Gothic",system-ui,sans-serif;color:#18212b;background:#f7f8fa}header{display:flex;justify-content:space-between;align-items:center;padding:18px 5vw;background:#fff;border-bottom:1px solid #e5e8ec}.brand{font-weight:800;letter-spacing:.02em;color:#17202a;text-decoration:none}nav a{margin-left:20px;color:#3f4b56;text-decoration:none;font-size:14px}main{max-width:1400px;margin:auto;padding:28px 5vw}.head{display:flex;justify-content:space-between;align-items:end;margin-bottom:18px}.eyebrow{font-size:12px;color:#687481;letter-spacing:.08em;margin:0 0 7px}.head h1{margin:0;font-size:30px}.meta{color:#5b6670}.status{padding:8px 12px;border:1px solid #dbe1e7;border-radius:999px;background:#fff}.tabs{display:flex;gap:6px;overflow-x:auto;white-space:nowrap;margin-bottom:18px}.tabs a{padding:11px 16px;border:1px solid #d9dfe5;border-radius:8px;background:#fff;color:#27333e;text-decoration:none;min-height:44px}.tabs a.active{background:#172a3a;color:white}.grid{display:grid;grid-template-columns:minmax(0,1fr) 330px;gap:18px}.panel{background:#fff;border:1px solid #e1e6eb;border-radius:10px;padding:18px;min-width:0}.panel h2{margin:0 0 8px;font-size:20px}.note{font-size:14px;color:#65717c}.table-wrap{overflow-x:auto}.data{width:100%;border-collapse:collapse;font-variant-numeric:tabular-nums}.data th,.data td{padding:10px 8px;border-bottom:1px solid #edf0f2;white-space:nowrap;text-align:right}.data th:nth-child(2),.data td:nth-child(2){text-align:left}.data th{font-size:12px;color:#65717c}.data td{font-size:14px}.player{font-weight:700}.sponsor{display:block;font-size:12px;color:#7a858f;font-weight:400;margin-top:2px}.band{font-size:12px;color:#385b78;background:#edf4f9;border-radius:4px;padding:3px 6px}.win{font-weight:800}.evolution{min-height:180px}.metric{font-size:32px;font-weight:800;font-variant-numeric:tabular-nums}.empty{padding:30px 0;color:#6f7a84}@media(max-width:800px){header{display:block}nav{margin-top:12px;display:flex;overflow-x:auto;white-space:nowrap}nav a{margin:0 16px 0 0}.grid{grid-template-columns:1fr}.head{display:block}.status{display:inline-block;margin-top:10px}.panel{padding:14px}main{padding:20px 3vw}.data th,.data td{padding:9px 7px}}
'''
def fmt(v): return "—" if v is None else str(v)
def main():
    d=json.loads((C/"OK_OPEN_2026_PRE_PUBLIC_MASTER.json").read_text(encoding="utf-8")); rows=sorted(d["records"],key=lambda r:(r.get("official_klpga_rank") is None,r.get("official_klpga_rank") or 9999,str(r["player_id"])))
    OUT.mkdir(parents=True,exist_ok=True); (OUT/"assets").mkdir(exist_ok=True); (OUT/"assets/bands.css").write_text(CSS,encoding="utf-8")
    tabs=''.join(f'<a class="{"active" if x=="대회" else ""}" href="{("index.html" if x=="대회" else x.lower()+"/index.html")}">{x}</a>' for x in ["대회","R1","R2","FINAL"])
    trs=[]
    for r in rows:
        name=escape(str(r.get("current_official_player_name") or "—")); sponsor=escape(str(r.get("current_official_sponsor") or "—")); band=escape(str(r.get("neo_performance_band") or "INSUFFICIENT_EVIDENCE")); win= r.get("win_probability"); wt="—" if win is None else f"{float(win)*100:.2f}%"
        trs.append(f'<tr><td><span class="band">{band}</span></td><th scope="row"><span class="player">{name}</span><span class="sponsor">{sponsor}</span></th><td>{fmt(r.get("official_klpga_rank"))}</td><td>{fmt(r.get("sg_total_rank"))}</td><td class="win">{wt}</td></tr>')
    html=f'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NEO GOLF DATA · OK저축은행 읏맨 오픈</title><link rel="stylesheet" href="assets/bands.css"></head><body><header><a class="brand" href="/">NEO GOLF DATA</a><nav><a href="/">홈</a><a href="#tournament">대회</a><a href="#forecast">예측 기록</a><a href="#deep-dive">DEEP DIVE</a><a href="#about">NEO 소개</a></nav></header><main><section class="head" id="tournament"><div><p class="eyebrow">대회</p><h1>OK저축은행 읏맨 오픈</h1><p class="meta">2026.09.04 — 09.06 · 포천아도니스 · 54홀 · 스트로크 플레이</p></div><strong class="status">PRE</strong></section><nav class="tabs" aria-label="대회 단계">{tabs}</nav><div class="grid"><section class="panel"><h2>참가자 데이터 <small>120명</small></h2><p class="note">대회 전 상태 · NEO 경기력 등급은 사전 검증된 경기력 증거를 통계적으로 구분한 밴드입니다. 공식 순위·예상 순위·우승 순위가 아닙니다.</p><div class="table-wrap"><table class="data"><thead><tr><th>NEO 경기력 등급</th><th>선수<br><small>공식 스폰서</small></th><th>KLPGA K-RANKING</th><th>SG Total 순위</th><th>우승확률</th></tr></thead><tbody>{''.join(trs)}</tbody></table></div></section><aside class="panel evolution" id="forecast"><p class="eyebrow">PRE · 예측 확정</p><h2>우승 가능성 변화</h2><p class="note">현재 공개된 사전 체크포인트</p><div class="metric">{(f"{float(rows[0].get('win_probability'))*100:.2f}%" if rows and rows[0].get('win_probability') is not None else '—')}</div><p class="note">선택한 선수의 PRE 우승확률</p></aside></div></main></body></html>'''
    (OUT/"index.html").write_text(html,encoding="utf-8")
    for stage in ["r1","r2","final"]:
        t=OUT/stage; t.mkdir(exist_ok=True); (t/"index.html").write_text(html.replace('class="active" href="index.html"','href="../index.html"'),encoding="utf-8")
    print(OUT); return 0
if __name__=="__main__": raise SystemExit(main())
