"""Build immutable V1 historical truth artifacts without fabricating gaps."""
from __future__ import annotations
import argparse,hashlib,json,sqlite3,sys
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1];CONTENT=ROOT/"content"/"website_v2";DOCS=ROOT/"docs"
sys.path.insert(0,str(ROOT/"src"))
def load(path):return json.loads(Path(path).read_text(encoding="utf-8"))
def sha(path):return hashlib.sha256(Path(path).read_bytes()).hexdigest()
def write(path,obj):Path(path).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
def main():
 p=argparse.ArgumentParser();p.add_argument("--db",type=Path,required=True);a=p.parse_args()
 frozen_path=CONTENT/"NEO_RANKING_V1_REDTEAM_BACKTEST.json";sg_path=CONTENT/"historical_sg_warehouse_corrected.json";frozen=load(frozen_path);sg=load(sg_path);kindex=load(CONTENT/"HISTORICAL_KRANKING_SNAPSHOT_INDEX_V1.json")
 events=sorted({x["event"] for x in frozen["observations"]});sg_meta={str(r.get("game_code")):{"name":r.get("tournament"),"season":r.get("season"),"retrieved_at":r.get("retrieved_at")} for r in sg.get("records",()) if r.get("game_code")}
 with sqlite3.connect(f"file:{a.db}?mode=ro",uri=True) as c:
  tm={str(g):{"tournament_name":n,"season":s,"start_date":sd,"end_date":ed} for g,n,s,sd,ed in c.execute("SELECT game_code,event_name,season,start_date,end_date FROM tournament_master")}
  names={str(pid):name for pid,name in c.execute("SELECT player_id,player_name FROM player_master")}
  entries={(str(g),str(pid)):{"player_name":name,"source":source,"collected_at":at} for g,pid,name,source,at in c.execute("SELECT game_code,player_code,player_name_display,source,collected_at FROM tournament_entry")}
 mappings=[];coverage=[];field_summaries=[];field_records=[];sg_hash=sha(sg_path)
 for event in events:
  meta=tm[event]; verified_entry=[v for (g,_),v in entries.items() if g==event and v["collected_at"] and v["collected_at"][:10] < meta["start_date"]]
  field_class="VERIFIED_PRE_EVENT_ENTRY" if verified_entry else "SG_ROW_RECONSTRUCTED";field_verified=bool(verified_entry)
  mappings.append({"game_code":event,"tournament_name":sg_meta.get(event,{}).get("name") or meta["tournament_name"],"season":meta["season"],"start_date":meta["start_date"],"end_date":meta["end_date"],"latest_available_pre_event_K_week":None,"K_ranking_publication_date":None,"temporal_gap_days":None,"status":"K_TEMPORAL_MAPPING_UNVERIFIED","reason":"official service exposes week identifiers but no verified publication-date evidence; no ISO-week date inference accepted"})
  event_obs=[r for r in frozen["observations"] if r["event"]==event];field_summaries.append({"game_code":event,"field_provenance":field_class,"pre_event_field_verified":field_verified,"player_count":len(verified_entry) if field_verified else len({r["player_id"] for r in event_obs}),"source":"tournament_entry read-only DB snapshot" if field_verified else "historical_sg_warehouse_corrected.json","source_sha256":None if field_verified else sg_hash,"source_timestamp":min(v["collected_at"] for v in verified_entry) if field_verified else sg_meta.get(event,{}).get("retrieved_at"),"entry_status_available":False})
  for r in event_obs:
   ent=entries.get((event,r["player_id"]));field_records.append({"game_code":event,"player_id":r["player_id"],"player_name":ent["player_name"] if ent else names.get(r["player_id"]),"entry_status":None,"entry_status_reason":"official source does not expose preserved status","field_provenance":"VERIFIED_PRE_EVENT_ENTRY" if ent and field_verified else "SG_ROW_RECONSTRUCTED","pre_event_field_verified":bool(ent and field_verified),"source":ent["source"] if ent and field_verified else "historical_sg_warehouse_corrected.json","source_timestamp":ent["collected_at"] if ent and field_verified else sg_meta.get(event,{}).get("retrieved_at"),"source_sha256":None if ent and field_verified else sg_hash})
  coverage.append({"game_code":event,"K_historical_snapshot_available":False,"K_temporal_mapping_verified":False,"pre_event_field_verified":field_verified,"field_provenance":field_class,"frozen_V1_available":bool(event_obs),"outcome_available":all(r.get("outcome_joined") for r in event_obs),"SG_outcome_available":all(r.get("target_sg_total") is not None for r in event_obs),"eligible_for_direct_K_vs_NEO":False,"exclusion_reasons":["K_TEMPORAL_MAPPING_UNVERIFIED"]+([] if field_verified else ["PRE_EVENT_FIELD_UNVERIFIED"])})
 mapping_doc={"schema_version":"neo_tournament_k_week_mapping_v1","publication_date_policy":"verified evidence only; ISO week conversion prohibited","records":mappings};write(CONTENT/"TOURNAMENT_K_WEEK_MAPPING_V1.json",mapping_doc)
 field_doc={"schema_version":"neo_historical_field_provenance_v1","classification_order":["VERIFIED_PRE_EVENT_ENTRY","VERIFIED_START_LIST","RESULT_DERIVED_FIELD","SG_ROW_RECONSTRUCTED","UNKNOWN"],"summaries":field_summaries,"records":field_records};write(CONTENT/"HISTORICAL_FIELD_PROVENANCE_V1.json",field_doc)
 field_lookup={(r["game_code"],r["player_id"]):r for r in field_records};rows=[]
 for r in frozen["observations"]:
  event=r["event"];meta=tm[event];fld=field_lookup[(event,r["player_id"])]
  rows.append({"game_code":event,"tournament_id":event,"tournament_name":sg_meta.get(event,{}).get("name") or meta["tournament_name"],"season":meta["season"],"tournament_start_date":meta["start_date"],"player_id":r["player_id"],"player_name":fld["player_name"],"pre_event_truth":{"field_provenance":fld["field_provenance"],"pre_event_field_verified":fld["pre_event_field_verified"],"K_ranking_week":None,"K_ranking_publication_date":None,"K_rank":None,"K_ranking_value":None,"K_source_hash":None,"K_status":"K_TEMPORAL_MAPPING_UNVERIFIED"},"frozen_model":{"NEO_V1_rank":r["neo_rank"],"NEO_V1_score":r["neo_score"],"V1_feature_cutoff_date":meta["start_date"],"V1_max_feature_date":r["max_feature_date"],"V1_prior_sample_count":r["prior_sample_count"],"V1_feature_contributions":r["feature_contributions"]},"outcome":{"finish_position":r["finish_position"],"made_cut":r["made_cut"],"withdrawn":r["withdrawn"],"disqualified":r["disqualified"],"tournament_SG_total":r["target_sg_total"]},"validation":{"future_leakage":not r["max_feature_date"]<meta["start_date"],"outcome_joined":r["outcome_joined"],"K_point_in_time_verified":False,"field_point_in_time_verified":fld["pre_event_field_verified"],"player_mapping_verified":r["outcome_joined"]}})
 validation={"future_leakage_count":sum(r["validation"]["future_leakage"] for r in rows),"K_snapshot_after_start_count":0,"silent_current_W35_substitution_count":0,"duplicate_tournament_player_count":len(rows)-len({(r["game_code"],r["player_id"]) for r in rows}),"duplicate_K_rank_count":0,"invalid_player_mapping_count":sum(not r["validation"]["player_mapping_verified"] for r in rows),"fabricated_K_rank_count":sum(r["pre_event_truth"]["K_rank"] is not None and not r["validation"]["K_point_in_time_verified"] for r in rows),"fabricated_entry_status_count":sum(f["entry_status"] is not None for f in field_records),"frozen_V1_config_changed":False,"insufficient_sample_force_ranked_count":sum(r["frozen_model"]["V1_prior_sample_count"]<10 for r in rows)}
 truth={"schema_version":"neo_historical_truth_warehouse_v1","immutability":"append new version; never overwrite frozen upstream artifacts","source_artifacts":{"frozen_V1_redteam":{"path":frozen_path.name,"sha256":sha(frozen_path)},"corrected_SG":{"path":sg_path.name,"sha256":sg_hash},"K_snapshot_index":{"path":"HISTORICAL_KRANKING_SNAPSHOT_INDEX_V1.json","sha256":sha(CONTENT/"HISTORICAL_KRANKING_SNAPSHOT_INDEX_V1.json")}},"record_count":len(rows),"tournament_count":len(events),"validation":validation,"records":rows}
 core=json.dumps(truth,sort_keys=True,separators=(",",":"),ensure_ascii=False);truth["deterministic_fingerprint"]=hashlib.sha256(core.encode()).hexdigest();write(CONTENT/"NEO_HISTORICAL_TRUTH_WAREHOUSE_V1.json",truth)
 benchmark={"schema_version":"neo_k_vs_neo_v1_benchmark_v1","status":"NOT_EVALUABLE","directly_comparable_tournaments":0,"comparable_player_events":0,"official_K_metrics":None,"frozen_NEO_V1_metrics":None,"metrics_won_by_K":[],"metrics_won_by_NEO":[],"inconclusive_metrics":["finish Spearman","SG correlation","Top10","Top20","made-cut AUC","incremental predictive value","rank divergence"],"reason":"official K weeks are partially recoverable, but publication dates and therefore pre-event temporal mappings are unverified; current ranks were not substituted"};write(CONTENT/"K_VS_NEO_V1_BENCHMARK_V1.json",benchmark)
 coverage_doc={"schema_version":"neo_historical_truth_coverage_v1","total_tournaments":len(events),"fully_verified_tournaments":sum(x["eligible_for_direct_K_vs_NEO"] for x in coverage),"partially_verified_tournaments":len(coverage),"unverified_tournaments":0,"records":coverage};write(CONTENT/"HISTORICAL_TRUTH_COVERAGE_V1.json",coverage_doc)
 report=["# NEO Ranking Historical Truth Warehouse V1","","> DATA FOUNDATION: **PARTIAL_FOUNDATION**","> NEO V1 PUBLIC RELEASE: **REJECT**","","## Recovery conclusions","",f"- Historical official K-Ranking: PARTIAL — {kindex['verified_week_count']} verified weekly responses, limited to {kindex['available_selector_weeks'][-1]} through {kindex['available_selector_weeks'][0]}.","- Publication dates: unverified. Week identifiers were not converted into assumed publication dates.",f"- Historical field truth: PARTIAL — {sum(x['pre_event_field_verified'] for x in coverage)}/{len(events)} tournaments have a preserved pre-event entry snapshot; all remaining fields are SG-row reconstructions.","","## Coverage","",f"- Total tournaments: {len(events)}",f"- Fully verified/directly comparable: 0",f"- Partially verified: {len(events)}",f"- Comparable player-events: 0",f"- Frozen V1 and outcomes: {len(rows)} player-events retained.","","## K vs frozen V1","","Direct benchmark and rank-divergence tests were not run. Without verified publication dates, selecting a weekly snapshot as pre-event truth would be an inference and could introduce after-start data.","","## Hard validation","",*[f"- {k}: {v}" for k,v in validation.items()],"","## Remaining blockers","","1. Official publication-date evidence for each K-Ranking week.","2. Historical K snapshots before 2025-W35, which the current official selector does not expose.","3. Pre-event entry/start-list evidence for 81 of 82 tournaments.","","The warehouse keeps every missing K value and entry status null with an explicit reason. No current-W35 substitution or fabricated historical value is present."]
 (DOCS/"NEO_HISTORICAL_TRUTH_WAREHOUSE_V1_AUDIT.md").write_text("\n".join(report)+"\n",encoding="utf-8")
 print(json.dumps({"tournaments":len(events),"records":len(rows),"verified_K_weeks":kindex["verified_week_count"],"verified_fields":sum(x["pre_event_field_verified"] for x in coverage),"fully_verified":0,"verdict":"PARTIAL_FOUNDATION","validation":validation},ensure_ascii=False));return 0
if __name__=="__main__":raise SystemExit(main())
